FROM node:20-alpine AS base

WORKDIR /app
COPY package*.json ./

# ---- Dev ----
FROM base AS dev

RUN apk add --no-cache openssl
RUN npm install
COPY . .
RUN npx prisma generate

EXPOSE 3000

CMD ["sh", "-c", "npm install && npm run start:dev"]

# ---- Prod ----
FROM base AS prod

RUN npm ci
COPY . .
RUN npx prisma generate
RUN npm run build

EXPOSE 3000

CMD ["sh", "-c", "npx prisma migrate deploy && npm run start:prod"]
